### ISSUE TITLE
dbsetup.php  غير موجود

### ISSUE THREAD

**Issue by alidz1982** [mo7amed-hussein/free-apps-store-system#2]
dbsetup.php  غير موجود

**Comment by mo7amed-hussein** [comment]
اعتذر اخي  لعدم اضافة ذلك الملف 
فالملف appstore.sql 
سيؤدي الغرض كما تعلم
شكرا

**Comment by alidz1982** [comment]
تم التنصيب بنجاح...ماشاءالله...الله يوفقك لكل خير
