### ISSUE TITLE
اضافة ستايلات

### ISSUE THREAD

**Issue by alidz1982** [mo7amed-hussein/free-apps-store-system#3]
السلام عليكم

اذا امكن اخي اضافة ستايلات يكون افضل...وشكرا

**Comment by mo7amed-hussein** [comment]
شكرا يا صديقي 
اثناء عملي علي هذا المشروع كان تركيزي علي 
php , mysql 
بشكل كبير , وساحاول قريبا ان شاء الله للعمل علي الاستايلات

**Comment by alidz1982** [comment]
موفق ان شاءالله
