### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by Buids** [mo7amed-hussein/free-apps-store-system#4]
It's unable to login even when password and email fields are correct. Error: either username or password is not correct.

Please what could be the cause?

**Comment by mo7amed-hussein** [comment]
i see that web page is no longer exist , have u hosted it locally ??

**Comment by Buids** [comment]
@mo7amed-hussein yes

**Comment by mo7amed-hussein** [comment]
ok , please double check that u created database using appstore.sql and it contains users as admin

**Comment by Buids** [comment]
@mo7amed-hussein Thank you. I have gotten through this stage.
