### ISSUE TITLE
Bootstrap Lib

### ISSUE THREAD

**Issue by Buids** [mo7amed-hussein/free-apps-store-system#5]
Pls can you give me the link for the bootstrap library, where it was downloaded. Pls

**Comment by mo7amed-hussein** [comment]
i do not remember the link , but it might be this one https://github.com/twbs/bootstrap/archive/v3.3.7.zip from here https://blog.getbootstrap.com/2016/07/25/bootstrap-3-3-7-released/

**Comment by Buids** [comment]
@mo7amed-hussein Thank you
